version: '3.8'

services:
    dev_mongodb:
        image: mongo:5.0.2
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        ports:
            - $MONGODB_DEV_PORT:$MONGODB_DEV_DOCKER_PORT
        volumes:
            - db:/dev_data/dev_db
    dev_app:
        depends_on:
            - dev_mongodb
        build: ./playwright-common-architect
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $NODE_DEV_PORT:$NODE_DEV_DOCKER_PORT
        environment:
            - DB_HOST=dev_mongodb
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_DEV_DATABASE
            - DB_PORT=$MONGODB_DEV_DOCKER_PORT
        stdin_open: true
        tty: true

volumes:
    db:
