version: '3.8'

services:
    mongodb:
        image: mongo:5.0.2
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        ports:
            - $MONGODB_STAGE_PORT:$MONGODB_STAGE_DOCKER_PORT
        volumes:
            - db:/stage_data/stage_db
    app:
        depends_on:
            - mongodb
        build: ./playwright-common-architect
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $NODE_STAGE_PORT:$NODE_STAGE_DOCKER_PORT
        environment:
            - DB_HOST=mongodb
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_STAGE_DATABASE
            - DB_PORT=$MONGODB_DOCKER_PORT
        stdin_open: true
        tty: true

volumes:
    db:
